name: Build and Test

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger workflow on pull requests targeting the main branch

jobs:
  build_and_test:
    runs-on: ubuntu-latest  # Run tests on an Ubuntu machine

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checkout the code from your repository

      - name: Set up CMake and build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make  # Install dependencies for CMake, g++, and make

      - name: Build the project with Makefile
        run: |
          make  # Use make to build the project and run the tests

      - name: Run the tests
        run: |
          cd build && ./run_tests  # Change to the build directory and run tests

      - name: Clean up the build directory
        run: |
          make clean  # Clean up build files after tests (optional)
